### PR TITLE
Ignore `window.fetch` network error

### LINKED ISSUE #37: exclude fetchApi "Failed to fetch" from ignores
Currently, as the API states, you discard instance of `TypeError`, however, the fetchApi `Failed to fetch` exception is of type `TypeError`.
One of the common reasons that this error occurs can be network connection issues.
Is it possible to include this exception? 
The main reason I want to add a retry mechanism is incase the user had a bad internet connection during that second where the request was going out

From [Fetch documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch):

> A fetch() promise will reject with a TypeError when a network error is encountered or CORS is misconfigured on the server-side

Current workaround:

```js
 pRetry(async () => {
        try {
            return await fetchRequest()
        } catch (error) {
            if (error instanceof TypeError && error.message === 'Failed to fetch') {
                throw new Error('Failed to fetch')
            }
            throw error;
        }
    }, {
        retries: 2,
        onFailedAttempt,
    });
```

Thanks

### PR DESCRIPTION
**Pull request by oreporan**
Fixes #37

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ const pRetry = (input, options) => new Promise((resolve, reject) => {
 			if (error instanceof AbortError) {
 				operation.stop();
 				reject(error.originalError);
-			} else if (error instanceof TypeError) {
+			} else if (error instanceof TypeError && error.message !== 'Failed to fetch') {
```
Comment (acostalima) [inline index.js:51]: Shouldn't we lax this condition a bit? Checking the error message for an exact match is [very restrictive](https://github.com/whatwg/fetch/issues/526#issuecomment-554604080).

Comment (oreporan) [reply index.js:51]: Yeah I agree, matching the string is ugly, have a better idea?

Comment (acostalima) [reply index.js:51]: Well, you're right. I had something else in mind but it will just overcomplicate things. The issue is documented in the README, so I guess it's alright. 💪

Comment (oreporan) [reply index.js:51]: so whats the next step? :)

Comment (acostalima) [reply index.js:51]: @sindresorhus will come back to you soon

File: readme.md [hunk 2]
```diff
@@ -38,7 +38,7 @@ const run = async () => {
 
 Returns a `Promise` that is fulfilled when calling `input` returns a fulfilled promise. If calling `input` returns a rejected promise, `input` is called again until the maximum number of retries is reached. It then rejects with the last rejection reason.
 
-It doesn't retry on `TypeError` as that's a user error.
+It doesn't retry on `TypeError` as that's a user error. The only exclusion is fetchApi's 'Failed to fetch' error which can be a network error. See [the docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), and [this issue](https://github.com/whatwg/fetch/issues/526)
```
Comment (sindresorhus) [inline readme.md:41]: I think this sentence could be written better.

You also need to update index.d.ts

Comment (oreporan) [reply readme.md:41]: Can you help me out with the wording? it seems fine for me

File: .vscode/settings.json [hunk 3]
```diff
@@ -0,0 +1 @@
+{}
```
Comment (acostalima) [inline .vscode/settings.json:1]: `.vscode` should not be checked in.

**Review by acostalima — CHANGES_REQUESTED** [review]

File: readme.md (hunk 2 above)
Comment (acostalima) [reply readme.md:41]: May I suggest the following:

"It doesn't retry on `TypeError` as that's a user error. The only exclusion to this logic is when `TypeError` is thrown by `fetch`'s API with the message 'Failed to fetch', which [indicates that a request was not successful due to a network error](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Checking_that_the_fetch_was_successful). However, beware that `fetch` may throw `TypeError` with different error messages on different platforms for similar situations. See https://github.com/whatwg/fetch/issues/526#issuecomment-554604080."

Better? 🤔

Comment (acostalima) [reply readme.md:41]: ping @sindresorhus @oreporan

Comment (oreporan) [reply readme.md:41]: Whatever @sindresorhus suggests as the text...Let me know

Comment (sindresorhus) [reply readme.md:41]: What @acostalima wrote looks good to me.

File: test.js [hunk 4]
```diff
@@ -48,6 +48,20 @@ test('no retry on TypeError', async t => {
 	t.is(i, 1);
 });
 
+test('retry on TypeError - failed to fetch', async t => {
+	const typeErrorFixture = new TypeError('Failed to fetch');
+	let i = 0;
```
Comment (sindresorhus) [inline test.js:53]:
```suggestion
	let index = 0;
```

File: test.js [hunk 5]
```diff
@@ -48,6 +48,20 @@ test('no retry on TypeError', async t => {
...
+
+	const ret = await pRetry(async attemptNumber => {
```
Comment (sindresorhus) [inline test.js:55]:
```suggestion
	const returnValue = await pRetry(async attemptNumber => {
```
