### PR TITLE
Fix retrying on network error in Firefox and Safari

### LINKED ISSUE #51: Firefox doesn't retry on TypeError: NetworkError
The error I'm receiving is "TypeError: NetworkError when attempting to fetch resource."
And p-retry doesn't retry at all.

### PR DESCRIPTION
**Pull request by Woyken**
Fixes #51

Added missing dot(".") at the end of Firefox error message.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I wonder if this applies to Safari too as it uses a dot in this issue https://github.com/sindresorhus/p-retry/issues/41, but was also added without a dot.

// @peterj35

**Comment by Woyken** [comment]
Unfortunately, I don't have safari to check myself.

This [Gist](https://gist.github.com/keeth/d5d94dab40b4d697618c075e155197da) has the error written in comment with a dot "TypeError: The Internet connection appears to be offline."

Also quick google search revealed few images where it looks like it probably does end with a dot 
image 
([Source](https://twitter.com/tomayac/status/1038377137659625474))

I'll add it too

File: test.js [hunk 1]
```diff
@@ -62,6 +62,34 @@ test('retry on TypeError - failed to fetch', async t => {
...
+
+	const returnValue = await pRetry(async attemptNumber => {
+		await delay(40);
+		index++;
+		return attemptNumber === 3 ? fixture : Promise.reject(typeErrorFixture);
+	});
+
+	t.is(returnValue, fixture);
+	t.is(index, 3);
+});
```
Comment (sindresorhus) [inline test.js:91]: I don't see the point of these added tests. They don't really add anything.
